<div id="pnl_editdetailform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit detailform</div>
		<a id="pnl_editdetailform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editdetailform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editdetailform-form">

		<div class="form_row">
			<div class="form_label_col">ID(d)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetailform-txt_journald_id" class="easyui-textbox" mapping="journald_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Line</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetailform-txt_journald_line" class="easyui-numberbox" mapping="journald_line" style="width: 400px" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetailform-txt_journald_descr" class="easyui-textbox" mapping="journald_descr"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetailform-cbo_acc_id" class="easyui-combo" style="width: 400px" mapping="acc_id" display="acc_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">ID(h)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetailform-txt_journal_id" class="easyui-textbox" mapping="journal_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Amount</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetailform-txt_journald_idr" class="easyui-numberbox" mapping="journald_idr" style="width: 400px" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editdetailform-autoadd" type="checkbox"><label for="pnl_editdetailform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editdetailform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editdetailform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editdetailform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editdetailform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editdetailform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
