<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Voucher</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_journal_id" class="easyui-textbox" mapping="journal_id"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_journal_descr" class="easyui-textbox" mapping="journal_descr"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Bookdate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_journal_bookdate" class="easyui-textbox" mapping="journal_bookdate"  maxlength="200" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Duedate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_journal_duedate" class="easyui-textbox" mapping="journal_duedate"  maxlength="50" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Source</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_journal_source" class="easyui-textbox" mapping="journal_source"  maxlength="5" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_journal_isdisabled" class="easyui-checkbox c1" mapping="journal_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', disabled:false, checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_journal_isposted" class="easyui-checkbox c1" mapping="journal_isposted" data-options="label: 'Posted', labelPosition: 'after', disabled:false, checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_journal_isreversed" class="easyui-checkbox c1" mapping="journal_isreversed" data-options="label: 'Reversed', labelPosition: 'after', disabled:false, checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Channel</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_channel_id" class="easyui-textbox" mapping="channel_id"  maxlength="10" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Region</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_region_id" class="easyui-combo" style="width: 400px" mapping="region_id" display="region_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Branch</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_branch_id" class="easyui-combo" style="width: 400px" mapping="branch_id" display="branch_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Strukturunit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_strukturunit_id" class="easyui-combo" style="width: 400px" mapping="strukturunit_id" display="strukt_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Rekanan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_rekanan_id" class="easyui-combo" style="width: 400px" mapping="rekanan_id" display="rekanan_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Rekanan Sub</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_rekanansub_id" class="easyui-combo" style="width: 400px" mapping="rekanansub_id" display="rekanansub_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Periode</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_periode_id" class="easyui-combo" style="width: 400px" mapping="periode_id" display="periode_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_acc_id" class="easyui-combo" style="width: 400px" mapping="acc_id" display="acc_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Alamat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_journaltype_id" class="easyui-textbox" mapping="journaltype_id"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Sub1</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_sub1_id" class="easyui-combo" style="width: 400px" mapping="sub1_id" display="sub1_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Sub2</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_sub2_id" class="easyui-combo" style="width: 400px" mapping="sub2_id" display="sub2_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Currency</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_curr_id" class="easyui-combo" style="width: 400px" mapping="curr_id" display="curr_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 0px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editdetailgrid')">detail</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

