<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit User</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_user_id" class="easyui-textbox" mapping="user_id"  maxlength="14" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Username</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_user_name" class="easyui-textbox" mapping="user_name"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Username harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">User Fullname</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_user_fullname" class="easyui-textbox" mapping="user_fullname" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Fullname harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_user_email" class="easyui-textbox" mapping="user_email"  maxlength="150" style="width: 400px" data-options="multiline: false , required: true, validType: ['email'], invalidMessage: 'Email harus diisi dengan benar' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Password</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_user_password" class="easyui-textbox" mapping="user_password"  maxlength="255" style="width: 400px" data-options="multiline: false, disabled: true  ">
				<a id="pnl_edit-btn_changepassword" class="easyui-linkbutton" href="javascript:void(0)">Change</a>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_user_disabled" class="easyui-checkbox c1" mapping="user_disabled" data-options="label: 'Disabled', labelPosition: 'after', disabled:false, checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Main Group</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_group_id" class="easyui-combo" style="width: 400px" mapping="group_id" display="group_name" data-options="editable:false, valueField:'id', textField:'text' ">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 0px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editgroupsgrid')">Owned Groups</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

