<div id="pnl_editpicgrid">
	<div class="fgta-page-title">Daftar picgrid</div>
	<div id="pnl_editpicgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editpicgrid-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th type="check">chk</th>
					<th mapping="locpic_id">locpic_id</th>
					<th mapping="locpic_name">locpic_name</th>
					<th mapping="locpic_resp">locpic_resp</th>
					<th mapping="locpic_email">locpic_email</th>
					<th mapping="locpic_phone">locpic_phone</th>
					<th mapping="loc_id">loc_id</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 5px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">locpic_id</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">locpic_name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">locpic_resp</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">locpic_email</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">locpic_phone</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">loc_id</td>

				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_editpicgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editpicgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editpicgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
