<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">store_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_store_id" class="easyui-textbox" mapping="store_id"  maxlength="14" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">store_name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_store_name" class="easyui-textbox" mapping="store_name" uppercase="true" maxlength="30" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">company_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_company_id" class="easyui-combo" style="width: 400px" mapping="company_id" display="company_name" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">bussinesstype_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_bussinesstype_id" class="easyui-combo" style="width: 400px" mapping="bussinesstype_id" display="bussinesstype_name" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">loc_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_loc_id" class="easyui-combo" style="width: 400px" mapping="loc_id" display="loc_name" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

