<div id="pnl_list">
	<div class="fgta-page-title">Daftar</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="divisi_id">divisi_id</th>
					<th mapping="divisi_name">divisi_name</th>
					<th mapping="divisi_nameshort">divisi_nameshort</th>
					<th mapping="divisi_pic">divisi_pic</th>
					<th mapping="divisi_level">divisi_level</th>
					<th mapping="divisi_namereport">divisi_namereport</th>
					<th mapping="divisi_parent">divisi_parent</th>
					<th mapping="divisi_path">divisi_path</th>
					<th mapping="divisi_isgroup">divisi_isgroup</th>
					<th mapping="divisi_isdisabled">divisi_isdisabled</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Divisi/ Dept.</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Nama Pendek</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">PIC</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Level</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Nama di Laporan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Parent</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Path</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">isGroup</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Disabled</td>

				</tr>
			</thead>
		</table>
	</div>



</div>