<style>
	.login-wrapper {
		position: fixed;
		overflow-Y: scroll;
		/*border: 3px solid #ff2a2a; */
		display:flex;
		width: calc(100vw - (100vw - 100%));
		height: 100vh;
		align-items: center;
		justify-content: center;
		background-color: #ebe8f5		
	}

	.login-box {
		margin: 20px; width: 250px; 
		border: 1px solid #9d6da9; 
		padding-bottom: 25px; 
		background-color: white;
		border-bottom-right-radius: 25px;
		box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
	}


	@media screen and (max-width: 520px) {
		.login-wrapper {
			border: 0px;
			align-items: flex-start;
			justify-content: flex-start;
			padding: 0px;	
			background-color: #ffffff			
		}

		.login-box {
			margin: 0px;
			width: 100%;
			border: 0px;
			padding: 0px;
			box-shadow: none;
		}
	}

</style>


<div class="login-wrapper">


	<div class="login-box" >

		<div style="font-weight: bold; font-size: larger; margin-bottom: 18px; height: 116px; background-color: #9d6da9; text-align: right;
		background-image: url('images/kalista.png');
		background-position:  bottom right;
		background-repeat: no-repeat;
		">
			<!-- <img src="images/kalista.png" width="210px" height="116px" border="0px"> -->
		</div>
		
		<div style="margin-left: 10px;" >
			<div style="width:225px; margin-top: 20px; margin-bottom: 5px">Username</div>
			<div style="width:225px">
				<input id="obj_txt_username" class="easyui-textbox" style="width:100%">
			</div>
		</div>

		<div style="margin-left: 10px;" >
			<div style="width:225px; margin-top: 20px; margin-bottom: 5px">Password</div>
			<div style="width:225px">
				<input id="obj_txt_password" class="easyui-passwordbox" style="width:100%">
			</div>
		</div>


		<div style="margin-top: 20px; margin-left: 10px;">
			<a id="btn_login" class="easyui-linkbutton c8">Login</a>
		</div>


		<div style="margin-top: 25px; margin-left: 10px;">
			<input id="obj_chk_rememberme" class="easyui-checkbox" label="Remember Me" labelPosition="after" labelAlign="left" labelWidth="100px" data-options="">
		</div>


	</div> 


</div>