<div id="pnl_detpledit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit item Packing List</div>
		<a id="pnl_detpledit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_detpledit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_detpledit-txt_logshippl_id" class="easyui-textbox" mapping="logshippl_id" maxlength="13" style="width: 400px" data-options="disabled:true">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Barcode</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_detpledit-txt_logshippl_barcode" class="easyui-textbox" mapping="logshippl_barcode" maxlength="30" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Art</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_detpledit-txt_logshippl_art" class="easyui-textbox" mapping="logshippl_art" maxlength="30" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Mat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_detpledit-txt_logshippl_mat" class="easyui-textbox" mapping="logshippl_mat" maxlength="30" style="width: 400px">
			</div>
		</div>
		
		<div class="form_row">
			<div class="form_label_col">Col</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_detpledit-txt_logshippl_col" class="easyui-textbox" mapping="logshippl_col" maxlength="30" style="width: 400px">
			</div>
		</div>		


		<div class="form_row">
			<div class="form_label_col">Qty</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_detpledit-txt_logshippl_qty" class="easyui-numberbox" mapping="logshippl_qty" style="width: 400px" >
			</div>
		</div>


	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_detpledit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>
	

	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_detpledit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>	
	
</div>