<div id="pnl_detpllist">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Packing List</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_detpllist-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th type="check">chk</th>
					<th mapping="barcode">barcode</th>
					<th mapping="art">art</th>
					<th mapping="mat">mat</th>
					<th mapping="col">col</th>
					<th mapping="box">box</th>
					<th mapping="qty">qty</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000"></td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Barcode</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ART</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">MAT</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">COL</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Box</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Qty</td>
				</tr>
			</thead>
		</table>
		
		<div id="pnl_detpllist-dettools" style="margin-top: 10px; display: flex; justify-content: space-between">
			<div>
				<a id="pnl_detpllist-btn_rowdel" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Baris</a>
			</div>

			<div>
				<a id="pnl_detpllist-btn_rowadd" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
				<a id="pnl_detpllist-btn_upload" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left: 5px">Upload</a>
			</div>

			<div>
			</div>

		</div>
	</div>

</div>	