<div id="pnl_list">
	<div class="fgta-page-title">Daftar</div>


	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>		
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search_brand" class="easyui-combo" style="width: 100%" data-options="prompt:'Pilih Brand'">
			</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%" data-options="prompt:'PO ref / DM'">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>

	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="logship_id">logship_id</th>
					<th mapping="logship_ref">logship_ref</th>
					<th mapping="logship_date">logship_date</th>
					<th mapping="logship_po">logship_po</th>
					<th mapping="logship_dm">logship_dm</th>
					<th mapping="logshipmethod_id">logshipmethod_id</th>
					<th mapping="brand_id">brand_id</th>
					<th mapping="sea_id">sea_id</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ref</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">PO ref</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">DM</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Method</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Brand</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Sea</td>
				</tr>
			</thead>
		</table>
	</div>



</div>