<div id="pnl_selfld">
	<div id="pnl_selfld-txt_title" class="fgta-page-title">Pilih Fields</div>
	<div>
		<img id="pnl_selfld-img_schema" width="100" height="100">
	</div>



	<div id="pnl_selfld-pnl_header">
		<div class="fld-ent-title">Header</div>

		<div style="display: flex">
			<div style="width: 50%">
				<div class="fld-ent-field" style="margin-top: 10px; margin-bottom: 30px">
					<div class="fld-ent-label">Table</div>
					<div class="fld-ent-value">
						<input id="pnl_selfld-txt_header_table" class="easyui-textbox" style="width: 100%">
						<!-- <input class="easyui-textbox" style="width: 100%" data-options="disabled:true,editable:false,buttonText:'...',buttonAlign:'right',prompt:'Pilih t...'"> -->
					</div>
				</div>
				<input class="easyui-textbox" style="width: 200px" data-options="buttonText:'coba'">
				<div id="pnl_selfld-pnl_header-board"></div>
			</div>

			<div style="width: 50%; padding-top: 10px">
				<div>Query</div>
				<div>
					<input id="pnl_selfld-txt_header_query" class="easyui-textbox" style="width:400px; height:150px;" data-options="multiline:true, readonly:true">
				</div>
			</div>

		</div>

		<div style="margin-top: 20px; margin-bottom: 20px">
			<div class="fld-ent-field">
				<div class="fld-ent-label" style="padding-left: 10px"></div>			
				<div class="fld-ent-value">
					<a href="javascript:void(0)" onclick="$ui.datapreview(this)">preview</a>
				</div>			
			</div>

		</div>



	</div>


	<div id="pnl_selfld-pnl_items">
		<div class="fld-ent-title">Items</div>


		<div style="display: flex">
			<div style="width: 50%">

				<div class="fld-ent-field" style="margin-top: 10px; margin-bottom: 30px">
					<div class="fld-ent-label">Table</div>
					<div class="fld-ent-value">
						<input id="pnl_selfld-txt_items_table" class="easyui-textbox" style="width: 100%" data-options="editable:false,buttonText:'...',buttonAlign:'right',prompt:'Pilih...'">
					</div>
				</div>

				<div id="pnl_selfld-pnl_items-board"></div>

			</div>
			<div style="width: 50%; padding-top: 10px">
				<div>Query</div>
				<div>
					<input id="pnl_selfld-txt_items_query" class="easyui-textbox" style="width:400px; height:150px;" data-options="multiline:true, readonly:true">
				</div>
			</div>

		</div>			

		<div style="margin-top: 20px; margin-bottom: 20px">
			<div class="fld-ent-field">
				<div class="fld-ent-label" style="padding-left: 10px"></div>			
				<div class="fld-ent-value">
					<a href="javascript:void(0)" onclick="$ui.datapreview(this)">preview</a>
				</div>			
			</div>

		</div>


	</div>


	<div id="pnl_selfld-pnl_payments">
		<div class="fld-ent-title">Payments</div>


		<div style="display: flex">
			<div style="width: 50%">

				<div class="fld-ent-field" style="margin-top: 10px; margin-bottom: 30px">
					<div class="fld-ent-label">Table</div>
					<div class="fld-ent-value">
						<input id="pnl_selfld-txt_payments_table" class="easyui-textbox" style="width: 100%" data-options="editable:false,buttonText:'...',buttonAlign:'right',prompt:'Pilih...'">
					</div>
				</div>

				<div id="pnl_selfld-pnl_payments-board"></div>

			</div>
			<div style="width: 50%; padding-top: 10px">
				<div>Query</div>
				<div>
					<input id="pnl_selfld-txt_payments_query" class="easyui-textbox" style="width:400px; height:150px;" data-options="multiline:true, readonly:true">
				</div>
			</div>

		</div>			


		<div style="margin-top: 20px; margin-bottom: 20px">
			<div class="fld-ent-field">
				<div class="fld-ent-label" style="padding-left: 10px"></div>			
				<div class="fld-ent-value">
					<a href="javascript:void(0)" onclick="$ui.datapreview(this)">preview</a>
				</div>			
			</div>

		</div>


	</div>



	<div style="margin-top:50px; margin-bottom: 100px; margin-left: 10px">
		<div style="margin-bottom: 10px">
		Pastikan semua konfigurasi tabel telah benar dan sesuai.
		</div>
		<a href="javascript:void(0)" class="easyui-linkbutton c8">Simpan Konfigurasi</a>
	</div>



</div>

