<div id="pnl_seldb">
	<div class="fgta-page-title">Pilih Tipe Database</div>

	<div>
		Pilih tipe database yang digunakan oleh toko <span id="pnl_seldb-txt_storename" style="font-weight: bold">nama toko</span>.<br>
	</div>
	<div style="margin-top: 30px">
		<ul>
			<?php
			foreach ($this->supporteddatabase as $dbtype) {
			?>
			<li><a id="pnl_seldb-type-<?=$dbtype->id?>" href="javascript:void(0)" class="dbtype" enabled="false" dbtype="<?=$dbtype->id?>" onclick="$ui.lst_db_click(this)"><?=$dbtype->text?></a></li>
			<?php } ?>
		</ul>	
	</div>


</div>

