<?php require_once dirname(__FILE__).'/config-selstore.phtml' ?>
<?php require_once dirname(__FILE__).'/config-seldb.phtml' ?>
<?php require_once dirname(__FILE__).'/config-selscm.phtml' ?>
<?php require_once dirname(__FILE__).'/config-selfld.phtml' ?>
<?php require_once dirname(__FILE__).'/config-lstfld.phtml' ?>
<?php require_once dirname(__FILE__).'/config-lsttbl.phtml' ?>
<?php require_once dirname(__FILE__).'/config-preview.phtml' ?>
