<div id="pnl_selstore">
	<div class="fgta-page-title">Konfigurasi Etap Client</div>

	<div>
	Selamat Datang <b><?=$this->userdata->userfullname?></b>,<br><br>
	Program ini digunakan untuk melakukan konfigurasi etap client.<br>
	Silakan pilih toko yang akan anda setup saat ini.<br>
	</div>

	<ul>
		<?php
		foreach ($this->stores as $store) {
		?>
		<li><a href="javascript:void(0)" onclick="$ui.lst_store_click(this)" dbtype="<?=$store->dbtype?>" store_id="<?=$store->store_id?>" ><?=$store->store_name?></a></li>
		<?php } ?>
	</ul>

</div>
