<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Bank</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bank_id" class="easyui-textbox" mapping="bank_id" uppercase="true" maxlength="14" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Bank</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bank_name" class="easyui-textbox" mapping="bank_name" uppercase="true" maxlength="60" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bank_code" class="easyui-textbox" mapping="bank_code" uppercase="true" maxlength="30" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Phone</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bank_phone" class="easyui-textbox" mapping="bank_phone" uppercase="true" maxlength="30" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bank_email" class="easyui-textbox" mapping="bank_email"  maxlength="30" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_bank_isdisabled" class="easyui-checkbox c1" mapping="bank_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', disabled:false, checked: false">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Address</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bank_address" class="easyui-textbox" mapping="bank_address"  maxlength="255" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bank_city" class="easyui-textbox" mapping="bank_city"  maxlength="90" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Provincy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bank_prov" class="easyui-textbox" mapping="bank_prov"  maxlength="90" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Country</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_country_id" class="easyui-combo" style="width: 400px" mapping="country_id" display="country_name" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

