<div id="pnl_editrategrid">
	<div class="fgta-page-title">Daftar Currency Rate</div>
	<div id="pnl_editrategrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editrategrid-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th type="check">chk</th>
					<th mapping="currrate_date">currrate_date</th>
					<th mapping="currrate_value">currrate_value</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 5px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Value</td>

				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_editrategrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editrategrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editrategrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
