<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_regional_id" class="easyui-textbox" mapping="regional_id"  maxlength="13" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Regional</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_regional_name" class="easyui-textbox" mapping="regional_name" uppercase="true" maxlength="90" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Nama Pendek</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_regional_nameshort" class="easyui-textbox" mapping="regional_nameshort" uppercase="true" maxlength="10" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_regional_code" class="easyui-textbox" mapping="regional_code"  maxlength="10" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">NPWP</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_regional_npwp" class="easyui-textbox" mapping="regional_npwp"  maxlength="13" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Alamat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_regional_alamat" class="easyui-textbox" mapping="regional_alamat"  maxlength="250" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Provinsi</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_provinsi_id" class="easyui-combo" style="width: 400px" mapping="provinsi_id" display="provinsi_name" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Kota</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_kota_id" class="easyui-combo" style="width: 400px" mapping="kota_id" display="kota_name" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Kecamatan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_kecamatan_id" class="easyui-combo" style="width: 400px" mapping="kecamatan_id" display="kecamatan_name" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Desa/ Kelurahan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_desa_id" class="easyui-combo" style="width: 400px" mapping="desa_id" display="desa_name" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Telp.</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_regional_telp" class="easyui-textbox" mapping="regional_telp"  maxlength="50" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_regional_email" class="easyui-textbox" mapping="regional_email"  maxlength="50" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_regional_descr" class="easyui-textbox" mapping="regional_descr"  maxlength="50" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_regional_isdisabled" class="easyui-checkbox c1" mapping="regional_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', disabled:false, checked: false">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

