<div id="pnl_list">
	<div class="fgta-page-title">Daftar</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="regional_name">regional_name</th>
					<th mapping="regional_nameshort">regional_nameshort</th>
					<th mapping="regional_code">regional_code</th>
					<th mapping="provinsi_name">provinsi_name</th>
					<th mapping="kota_name">kota_name</th>
					<th mapping="kecamatan_name">kecamatan_name</th>
					<th mapping="desa_name">desa_name</th>
					<th mapping="regional_telp">regional_telp</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Regional</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Nama Pendek</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Code</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Provinsi</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Kota</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Kecamatan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Desa/ Kelurahan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Telp.</td>

				</tr>
			</thead>
		</table>
	</div>



</div>