<div id="pnl_list">
	<div class="fgta-page-title">Daftar</div>


	<div id="pnl_list-pnl_head" style="display: flex;">
		<!-- Simple Query -->
		<div style="width: calc(100% - 65px); display: flex;">
			<div style="width: 100px;">Cari</div>
			<div style="width: 150px">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div>
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<div style="text-align: right; width: 65px; float: right;">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
	</div>

	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="logshipcostcomp_id">logshipcostcomp_id</th>
					<th mapping="logshipcostcomp_name">logshipcostcomp_name</th>
					<th mapping="logshipcostsrc_id">logshipcostsrc_id</th>
					<th mapping="logshipcostcomp_isdisabled">logshipcostcomp_isdisabled</th>

				</tr>
				<tr style="background-color: #cccccc">
					<td style="width: 100px; border-bottom: 1px solid #000000">logshipcostcomp_id</td>
					<td style="width: 100px; border-bottom: 1px solid #000000">logshipcostcomp_name</td>
					<td style="width: 100px; border-bottom: 1px solid #000000">logshipcostsrc_id</td>
					<td style="width: 100px; border-bottom: 1px solid #000000">logshipcostcomp_isdisabled</td>

				</tr>
			</thead>
		</table>
	</div>



</div>