<div id="pnl_list">
	<div class="fgta-page-title">Daftar</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="employee_nipp">employee_nipp</th>
					<th mapping="employee_name">employee_name</th>
					<th mapping="regional_name">regional_name</th>
					<th mapping="divisi_name">divisi_name</th>
					<th mapping="jabatan_name">jabatan_name</th>
					<th mapping="gol_name">gol_name</th>
					<th mapping="kontrak_name">kontrak_name</th>
					<th mapping="employee_datestart">employee_datestart</th>
					<th mapping="employee_npwp">employee_npwp</th>
					<th mapping="ptkp_name">ptkp_name</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">NIPP</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Karyawan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Regional</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Divisi</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Jabatan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Golongan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Kontrak</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Aktif Mulai</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">NPWP</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">PTKP</td>

				</tr>
			</thead>
		</table>
	</div>



</div>