<div id="pnl_editKomponenform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit</div>
		<a id="pnl_editKomponenform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editKomponenform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editKomponenform-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editKomponenform-txt_empkomp_id" class="easyui-textbox" mapping="empkomp_id"  maxlength="14" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Komponen</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editKomponenform-cbo_komp_id" class="easyui-combo" style="width: 400px" mapping="komp_id" display="komp_id" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Employee</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editKomponenform-txt_employee_id" class="easyui-textbox" mapping="employee_id"  maxlength="14" style="width: 400px" data-options="disabled: true">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editKomponenform-txt_empkomp_descr" class="easyui-textbox" mapping="empkomp_descr"  maxlength="250" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Amount</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editKomponenform-txt_empkomp_amount" class="easyui-numberbox" mapping="empkomp_amount" style="width: 400px;text-align: right;" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editKomponenform-autoadd" type="checkbox"><label for="pnl_editKomponenform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editKomponenform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editKomponenform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editKomponenform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editKomponenform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editKomponenform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
