<div id="pnl_editKomponengrid">
	<div class="fgta-page-title">Daftar Komponengrid</div>
	<div id="pnl_editKomponengrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editKomponengrid-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th type="check">chk</th>
					<th mapping="empkomp_id">empkomp_id</th>
					<th mapping="komp_name">komp_name</th>
					<th mapping="empkomp_descr">empkomp_descr</th>
          <th mapping="empkomp_amount" 
              data-options="field:'empkomp_amount',width:50, 
                formatter:function(value, row){                                  
                return parseInt(num).format(2, 3, '.', ',');}">empkomp_amount
          </th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 5px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Komponen</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Descr</td>
          <td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000;">Amount</td>
				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_editKomponengrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editKomponengrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editKomponengrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
