<div id="pnl_editdistrictform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit District</div>
		<a id="pnl_editdistrictform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editdistrictform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editdistrictform-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdistrictform-txt_district_id" class="easyui-textbox" mapping="district_id"  maxlength="14" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">District</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdistrictform-txt_district_name" class="easyui-textbox" mapping="district_name" uppercase="true" maxlength="90" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdistrictform-txt_city_id" class="easyui-textbox" mapping="city_id"  maxlength="14" style="width: 400px" data-options="disabled: true">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editdistrictform-autoadd" type="checkbox"><label for="pnl_editdistrictform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editdistrictform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editdistrictform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editdistrictform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editdistrictform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editdistrictform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
