<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit City</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_city_id" class="easyui-textbox" mapping="city_id"  maxlength="14" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">City Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_city_name" class="easyui-textbox" mapping="city_name" uppercase="true" maxlength="90" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Province</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_prov_id" class="easyui-combo" style="width: 400px" mapping="prov_id" display="prov_name" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 0px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editdistrictgrid')">district</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

