<?php require_once dirname(__FILE__).'/ship-list.phtml' ?>
<?php require_once dirname(__FILE__).'/ship-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/ship-selterm.phtml' ?>
<?php require_once dirname(__FILE__).'/ship-selmethod.phtml' ?>
<?php require_once dirname(__FILE__).'/ship-selbrand.phtml' ?>
<?php require_once dirname(__FILE__).'/ship-selsea.phtml' ?>
<?php require_once dirname(__FILE__).'/ship-selcurr.phtml' ?>
<?php require_once dirname(__FILE__).'/ship-selpartner.phtml' ?>
