<div id="pnl_selcurr">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Pilih Currency</div>
	</div>

	<div style="width: calc(100% - 65px); display: flex;">
		<div style="width: 100px;">Cari</div>
		<div style="width: 150px">
			<input id="pnl_selcurr-txt_search" class="easyui-textbox" style="width: 100%">
		</div>
		<div>
			<a href="javascript:void(0)" id="pnl_selcurr-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
		</div>
	</div>

	<div style="margin-top: 10px">
		<table id="pnl_selcurr-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th mapping="curr_id">id</th>
					<th mapping="curr_name">text</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td style="width: 100px; border-bottom: 1px solid #000000">Currency</td>
				</tr>
			</thead>
		</table>
	</div>

</div>