<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_kompgroup_id" class="easyui-textbox" mapping="kompgroup_id"  maxlength="13" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Group Komponen</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_kompgroup_name" class="easyui-textbox" mapping="kompgroup_name" uppercase="true" maxlength="50" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_kompgroup_code" class="easyui-textbox" mapping="kompgroup_code" uppercase="true" maxlength="20" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Rule</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_kompgroup_rule" class="easyui-textbox" mapping="kompgroup_rule"  maxlength="5" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_kompgroup_istax" class="easyui-checkbox c1" mapping="kompgroup_istax" data-options="label: 'Taxed', labelPosition: 'after', disabled:false, checked: false">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Periode</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_kompgroup_period" class="easyui-textbox" mapping="kompgroup_period"  maxlength="5" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_kompgroup_acc" class="easyui-textbox" mapping="kompgroup_acc"  maxlength="20" style="width: 400px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_kompgroup_isdisabled" class="easyui-checkbox c1" mapping="kompgroup_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', disabled:false, checked: false">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

