<div id="pnl_editpicform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit</div>
		<a id="pnl_editpicform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editpicform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editpicform-form">

		<div class="form_row">
			<div class="form_label_col">companypic_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpicform-txt_companypic_id" class="easyui-textbox" mapping="companypic_id"  maxlength="14" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">companypic_name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpicform-txt_companypic_name" class="easyui-textbox" mapping="companypic_name" uppercase="true" maxlength="90" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">companypic_resp</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpicform-txt_companypic_resp" class="easyui-textbox" mapping="companypic_resp" uppercase="true" maxlength="90" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">companypic_email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpicform-txt_companypic_email" class="easyui-textbox" mapping="companypic_email"  maxlength="90" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">companypic_phone</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpicform-txt_companypic_phone" class="easyui-textbox" mapping="companypic_phone"  maxlength="90" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">company_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpicform-txt_company_id" class="easyui-textbox" mapping="company_id"  maxlength="14" style="width: 400px" data-options="disabled: true">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editpicform-autoadd" type="checkbox"><label for="pnl_editpicform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editpicform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editpicform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editpicform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editpicform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editpicform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
