<div id="pnl_editbrandform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit</div>
		<a id="pnl_editbrandform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editbrandform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editbrandform-form">

		<div class="form_row">
			<div class="form_label_col">companybrand_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbrandform-txt_companybrand_id" class="easyui-textbox" mapping="companybrand_id"  maxlength="14" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">brand_name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbrandform-txt_brand_name" class="easyui-textbox" mapping="brand_name" uppercase="true" maxlength="90" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">brand_nameshort</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbrandform-txt_brand_nameshort" class="easyui-textbox" mapping="brand_nameshort" uppercase="true" maxlength="90" style="width: 400px" >
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbrandform-chk_brand_isdisabled" class="easyui-checkbox c1" mapping="brand_isdisabled" data-options="label: 'brand_isdisabled', labelPosition: 'after', disabled:false, checked: false">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">company_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbrandform-txt_company_id" class="easyui-textbox" mapping="company_id"  maxlength="14" style="width: 400px" data-options="disabled: true">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editbrandform-autoadd" type="checkbox"><label for="pnl_editbrandform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editbrandform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editbrandform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editbrandform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editbrandform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editbrandform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
