<div id="pnl_editbrandgrid">
	<div class="fgta-page-title">Daftar brandgrid</div>
	<div id="pnl_editbrandgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editbrandgrid-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th type="check">chk</th>
					<th mapping="companybrand_id">companybrand_id</th>
					<th mapping="brand_name">brand_name</th>
					<th mapping="brand_nameshort">brand_nameshort</th>
					<th mapping="brand_isdisabled">brand_isdisabled</th>
					<th mapping="company_id">company_id</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 5px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">companybrand_id</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">brand_name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">brand_nameshort</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">brand_isdisabled</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">company_id</td>

				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_editbrandgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editbrandgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editbrandgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
